---
platform: linux

inputs:
- name: pool-resource
  path: gopath/src/github.com/concourse/pool-resource

outputs:
- name: built-resource

run:
  path: gopath/src/github.com/concourse/pool-resource/ci/build
