FROM 140.211.168.97:5000/git:2.10.0

RUN echo "dash dash/sh boolean false" | debconf-set-selections
RUN DEBIAN_FRONTEND=noninteractive dpkg-reconfigure dash

RUN apt-get update \
 && apt-get install -y openssh-client

ADD assets/ /opt/resource/
RUN chmod +x /opt/resource/*

ADD built-out /opt/go/out
RUN chmod +x /opt/go/out

ADD test/ /opt/resource-tests/
RUN /opt/resource-tests/all.sh
